-- SPEC-026 v0.11 Phase 1a schema (§10 step 1).
-- Adds three tables backing App-track provider onboarding:
--   * provider_identities         — App-track identity + App Attest state
--   * provider_auth_policy        — cross-track WS proof-stage auth allowlist
--   * provider_auth_policy_pending — dual-approval workflow for admin exemptions
--   * provider_auth_policy_grants — immutable approval history for renewal caps
--
-- These live on the coordinator's Postgres stats DB. The money-path
-- provider_tokens table (SQLite, phase4-coordinator/internal/auth/tokens.go:248)
-- is unchanged; the mint transaction in SPEC-026 §4.1 step 7 needs to
-- coordinate across both DBs — implementer follows BUILD prompt.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'provider_onboarding') THEN
        CREATE ROLE provider_onboarding LOGIN;
    ELSE
        ALTER ROLE provider_onboarding LOGIN;
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS provider_identities (
    provider_id       TEXT PRIMARY KEY,
    identity_pubkey   BYTEA NOT NULL,
    attested          BOOLEAN NOT NULL DEFAULT FALSE,
    app_attest_key_id BYTEA NULL UNIQUE,
    first_seen_ts     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_provider_identities_first_seen
    ON provider_identities(first_seen_ts);

CREATE TABLE IF NOT EXISTS provider_register_nonces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id TEXT NOT NULL,
    source_ip   TEXT NOT NULL,
    nonce       TEXT NOT NULL,
    ts_utc      TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_provider_register_nonces_provider_nonce_ts
    ON provider_register_nonces(provider_id, nonce, ts_utc);

CREATE INDEX IF NOT EXISTS idx_provider_register_nonces_source_nonce_ts
    ON provider_register_nonces(source_ip, nonce, ts_utc);

CREATE INDEX IF NOT EXISTS idx_provider_register_nonces_created_at
    ON provider_register_nonces(created_at);

-- Bounded-retention hook for the replay cache. Runtime onboarding keeps only
-- SELECT/INSERT; operators run this SECURITY DEFINER function from cron or a
-- maintenance shell with a retain_for value >= the 65s replay window.
CREATE OR REPLACE FUNCTION prune_provider_register_nonces(retain_for INTERVAL DEFAULT INTERVAL '15 minutes')
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    deleted_count BIGINT;
BEGIN
    IF retain_for < INTERVAL '65 seconds' THEN
        RAISE EXCEPTION 'retain_for must be at least 65 seconds';
    END IF;

    DELETE FROM provider_register_nonces
     WHERE created_at < NOW() - retain_for;
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;

-- Cross-track: rows for BOTH `p_`-prefixed App-track and CLI-track opaque IDs.
CREATE TABLE IF NOT EXISTS provider_auth_policy (
    provider_id             TEXT PRIMARY KEY,
    kind                    TEXT NOT NULL CHECK (kind IN ('app', 'cli')),
    signature_exempt_until  TIMESTAMPTZ NULL,
    granted_by              TEXT NOT NULL,
    granted_reason          TEXT NOT NULL,
    granted_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_provider_auth_policy_exempt_until
    ON provider_auth_policy(signature_exempt_until)
    WHERE signature_exempt_until IS NOT NULL;

CREATE TABLE IF NOT EXISTS provider_auth_policy_cutover_runs (
    singleton_id  BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton_id),
    cutover_time  TIMESTAMPTZ NOT NULL,
    seeded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Dual-approval workflow. Empty until an operator issues an exemption grant.
CREATE TABLE IF NOT EXISTS provider_auth_policy_pending (
    pending_id       UUID PRIMARY KEY,
    provider_id      TEXT NOT NULL,
    requested_by     TEXT NOT NULL,
    requested_until  TIMESTAMPTZ NOT NULL,
    reason           TEXT NOT NULL,
    incident_id      TEXT NULL,
    approved_by      TEXT NULL,
    approved_at      TIMESTAMPTZ NULL,
    committed_at     TIMESTAMPTZ NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (approved_by IS NULL OR approved_by <> requested_by)
);

CREATE INDEX IF NOT EXISTS idx_provider_auth_policy_pending_provider_id
    ON provider_auth_policy_pending(provider_id);

CREATE INDEX IF NOT EXISTS idx_provider_auth_policy_pending_committed
    ON provider_auth_policy_pending(committed_at)
    WHERE committed_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_auth_policy_pending_open_incident
    ON provider_auth_policy_pending(provider_id, incident_id)
    WHERE incident_id IS NOT NULL AND committed_at IS NULL;

CREATE TABLE IF NOT EXISTS provider_auth_policy_grants (
    grant_id         UUID PRIMARY KEY,
    pending_id       UUID NULL UNIQUE REFERENCES provider_auth_policy_pending(pending_id),
    provider_id      TEXT NOT NULL,
    grant_source     TEXT NOT NULL DEFAULT 'operator' CHECK (grant_source IN ('operator', 'migration')),
    requested_by     TEXT NOT NULL,
    approved_by      TEXT NOT NULL,
    requested_until  TIMESTAMPTZ NOT NULL,
    reason           TEXT NOT NULL,
    incident_id      TEXT NULL,
    granted_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_provider_auth_policy_grants_provider_id
    ON provider_auth_policy_grants(provider_id, granted_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_auth_policy_grants_incident
    ON provider_auth_policy_grants(provider_id, incident_id)
    WHERE incident_id IS NOT NULL;

CREATE OR REPLACE FUNCTION seed_provider_auth_policy_cutover(
    p_cutover TIMESTAMPTZ,
    p_cli_provider_ids TEXT[] DEFAULT ARRAY[]::TEXT[]
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    inserted_app BIGINT := 0;
    inserted_cli BIGINT := 0;
    inserted_run BIGINT := 0;
    effective_cutover TIMESTAMPTZ;
BEGIN
    IF p_cutover IS NULL THEN
        RAISE EXCEPTION 'cutover time is required';
    END IF;
    IF p_cutover > NOW() + INTERVAL '5 minutes' THEN
        RAISE EXCEPTION 'cutover time cannot be in the future';
    END IF;

    INSERT INTO provider_auth_policy_cutover_runs (singleton_id, cutover_time)
    VALUES (TRUE, p_cutover)
    ON CONFLICT (singleton_id) DO NOTHING;
    GET DIAGNOSTICS inserted_run = ROW_COUNT;
    IF inserted_run <> 1 THEN
        RAISE EXCEPTION 'cutover seed already completed';
    END IF;

    SELECT cutover_time INTO effective_cutover
      FROM provider_auth_policy_cutover_runs
     WHERE singleton_id = TRUE
     FOR UPDATE;

    WITH inserted AS (
        INSERT INTO provider_auth_policy (
            provider_id, kind, signature_exempt_until, granted_by, granted_reason, granted_at
        )
        SELECT i.provider_id, 'app', effective_cutover + INTERVAL '7 days', 'migration', 'spec-026-cutover-legacy', effective_cutover
          FROM provider_identities i
         WHERE i.first_seen_ts <= effective_cutover
        ON CONFLICT (provider_id) DO NOTHING
        RETURNING provider_id, signature_exempt_until, granted_reason, granted_at
    ), grant_insert AS (
        INSERT INTO provider_auth_policy_grants (
            grant_id, pending_id, provider_id, grant_source, requested_by, approved_by,
            requested_until, reason, incident_id, granted_at
        )
        SELECT (
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 1, 8) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 9, 4) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 13, 4) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 17, 4) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 21, 12)
        )::UUID,
        NULL, provider_id, 'migration', 'migration', 'migration',
        signature_exempt_until, granted_reason, NULL, granted_at
          FROM inserted
        ON CONFLICT DO NOTHING
        RETURNING 1
    )
    SELECT COUNT(*) INTO inserted_app FROM inserted;

    WITH cli_ids AS (
        SELECT DISTINCT BTRIM(id) AS provider_id
          FROM unnest(COALESCE(p_cli_provider_ids, ARRAY[]::TEXT[])) AS id
         WHERE NULLIF(BTRIM(id), '') IS NOT NULL
           AND BTRIM(id) NOT LIKE 'p\_%' ESCAPE '\'
    ), inserted AS (
        INSERT INTO provider_auth_policy (
            provider_id, kind, signature_exempt_until, granted_by, granted_reason, granted_at
        )
        SELECT provider_id, 'cli', effective_cutover + INTERVAL '7 days', 'migration', 'spec-026-cutover-legacy', effective_cutover
          FROM cli_ids
        ON CONFLICT (provider_id) DO NOTHING
        RETURNING provider_id, signature_exempt_until, granted_reason, granted_at
    ), grant_insert AS (
        INSERT INTO provider_auth_policy_grants (
            grant_id, pending_id, provider_id, grant_source, requested_by, approved_by,
            requested_until, reason, incident_id, granted_at
        )
        SELECT (
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 1, 8) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 9, 4) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 13, 4) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 17, 4) || '-' ||
            SUBSTR(MD5('spec-026-cutover:' || provider_id || ':' || effective_cutover::TEXT), 21, 12)
        )::UUID,
        NULL, provider_id, 'migration', 'migration', 'migration',
        signature_exempt_until, granted_reason, NULL, granted_at
          FROM inserted
        ON CONFLICT DO NOTHING
        RETURNING 1
    )
    SELECT COUNT(*) INTO inserted_cli FROM inserted;

    RETURN inserted_app + inserted_cli;
END;
$$;

CREATE OR REPLACE FUNCTION request_provider_auth_policy_exemption(
    p_pending_id UUID,
    p_provider_id TEXT,
    p_requested_by TEXT,
    p_requested_until TIMESTAMPTZ,
    p_reason TEXT,
    p_incident_id TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    request_time TIMESTAMPTZ := NOW();
    used_exemption INTERVAL;
    requested_exemption INTERVAL;
BEGIN
    IF p_pending_id IS NULL THEN
        RAISE EXCEPTION 'pending_id is required';
    END IF;
    IF NULLIF(BTRIM(p_provider_id), '') IS NULL THEN
        RAISE EXCEPTION 'provider_id is required';
    END IF;
    IF p_requested_by !~ '^operator:[^[:space:]]+$' THEN
        RAISE EXCEPTION 'requested_by must use operator:<admin_id>';
    END IF;
    IF NULLIF(BTRIM(p_reason), '') IS NULL THEN
        RAISE EXCEPTION 'reason is required';
    END IF;
    IF p_requested_until <= request_time THEN
        RAISE EXCEPTION 'requested_until must be in the future';
    END IF;
    IF p_requested_until - request_time > INTERVAL '30 days' THEN
        RAISE EXCEPTION 'requested_until exceeds 30 day ceiling';
    END IF;
    IF p_requested_until - request_time > INTERVAL '7 days' AND NULLIF(BTRIM(COALESCE(p_incident_id, '')), '') IS NULL THEN
        RAISE EXCEPTION 'incident_id required for exemptions over 7 days';
    END IF;
    IF p_provider_id LIKE 'p\_%' ESCAPE '\' AND NOT EXISTS (
        SELECT 1 FROM provider_identities i WHERE i.provider_id = p_provider_id
    ) THEN
        RAISE EXCEPTION 'provider_id not found';
    END IF;
    PERFORM pg_advisory_xact_lock(26026, hashtext(BTRIM(p_provider_id)));
    IF NULLIF(BTRIM(COALESCE(p_incident_id, '')), '') IS NOT NULL AND EXISTS (
        SELECT 1 FROM provider_auth_policy_grants g
         WHERE g.provider_id = BTRIM(p_provider_id)
           AND g.incident_id = NULLIF(BTRIM(COALESCE(p_incident_id, '')), '')
    ) THEN
        RAISE EXCEPTION 'incident_id already used';
    END IF;
    -- Incident IDs allow the >7d break-glass TTL path, but do not reset the
    -- 30d exposure cap until a separately verified rotation event exists.
    SELECT COALESCE(SUM(GREATEST(g.requested_until - g.granted_at, INTERVAL '0 seconds')), INTERVAL '0 seconds')
      INTO used_exemption
      FROM provider_auth_policy_grants g
     WHERE g.provider_id = BTRIM(p_provider_id);
    requested_exemption := GREATEST(p_requested_until - request_time, INTERVAL '0 seconds');
    IF used_exemption + requested_exemption > INTERVAL '30 days' THEN
        RAISE EXCEPTION 'renewal cap exceeded';
    END IF;

    INSERT INTO provider_auth_policy_pending (
        pending_id, provider_id, requested_by, requested_until, reason, incident_id
    ) VALUES (
        p_pending_id,
        BTRIM(p_provider_id),
        BTRIM(p_requested_by),
        p_requested_until,
        BTRIM(p_reason),
        NULLIF(BTRIM(COALESCE(p_incident_id, '')), '')
    );
    RETURN p_pending_id;
END;
$$;

CREATE OR REPLACE FUNCTION approve_provider_auth_policy_exemption(
    p_pending_id UUID,
    p_approved_by TEXT
)
RETURNS TABLE (
    provider_id TEXT,
    requested_by TEXT,
    requested_until TIMESTAMPTZ,
    reason TEXT,
    incident_id TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    pending provider_auth_policy_pending%ROWTYPE;
    approval_time TIMESTAMPTZ := NOW();
    used_exemption INTERVAL;
    requested_exemption INTERVAL;
BEGIN
    IF p_approved_by !~ '^operator:[^[:space:]]+$' THEN
        RAISE EXCEPTION 'approved_by must use operator:<admin_id>';
    END IF;

    SELECT * INTO pending
      FROM provider_auth_policy_pending
     WHERE pending_id = p_pending_id
     FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'pending exemption not found';
    END IF;
    IF pending.committed_at IS NOT NULL THEN
        RAISE EXCEPTION 'pending exemption already committed';
    END IF;
    IF pending.requested_by = BTRIM(p_approved_by) THEN
        RAISE EXCEPTION 'dual_control_required';
    END IF;
    IF pending.requested_until <= approval_time THEN
        RAISE EXCEPTION 'requested_until must be in the future';
    END IF;
    PERFORM pg_advisory_xact_lock(26026, hashtext(pending.provider_id));
    IF pending.incident_id IS NOT NULL AND EXISTS (
        SELECT 1 FROM provider_auth_policy_grants g
         WHERE g.provider_id = pending.provider_id
           AND g.incident_id = pending.incident_id
    ) THEN
        RAISE EXCEPTION 'incident_id already used';
    END IF;
    -- See request_provider_auth_policy_exemption: incidents are unique but
    -- still counted against the cumulative exposure cap.
    SELECT COALESCE(SUM(GREATEST(g.requested_until - g.granted_at, INTERVAL '0 seconds')), INTERVAL '0 seconds')
      INTO used_exemption
      FROM provider_auth_policy_grants g
     WHERE g.provider_id = pending.provider_id;
    requested_exemption := GREATEST(pending.requested_until - approval_time, INTERVAL '0 seconds');
    IF used_exemption + requested_exemption > INTERVAL '30 days' THEN
        RAISE EXCEPTION 'renewal cap exceeded';
    END IF;

    UPDATE provider_auth_policy_pending
       SET approved_by = BTRIM(p_approved_by),
           approved_at = approval_time,
           committed_at = approval_time
     WHERE pending_id = p_pending_id;

    INSERT INTO provider_auth_policy (
        provider_id, kind, signature_exempt_until, granted_by, granted_reason, granted_at
    ) VALUES (
        pending.provider_id,
        CASE WHEN pending.provider_id LIKE 'p\_%' ESCAPE '\' THEN 'app' ELSE 'cli' END,
        pending.requested_until,
        BTRIM(p_approved_by),
        pending.reason,
        approval_time
    )
    ON CONFLICT (provider_id) DO UPDATE
       SET kind = EXCLUDED.kind,
           signature_exempt_until = EXCLUDED.signature_exempt_until,
           granted_by = EXCLUDED.granted_by,
           granted_reason = EXCLUDED.granted_reason,
           granted_at = EXCLUDED.granted_at;

    INSERT INTO provider_auth_policy_grants (
        grant_id, pending_id, provider_id, requested_by, approved_by,
        requested_until, reason, incident_id, granted_at
    ) VALUES (
        pending.pending_id,
        pending.pending_id,
        pending.provider_id,
        pending.requested_by,
        BTRIM(p_approved_by),
        pending.requested_until,
        pending.reason,
        pending.incident_id,
        approval_time
    );

    RETURN QUERY SELECT pending.provider_id, pending.requested_by, pending.requested_until, pending.reason, pending.incident_id;
END;
$$;

GRANT USAGE ON SCHEMA public TO provider_onboarding;

GRANT SELECT, INSERT, UPDATE ON provider_identities TO provider_onboarding;
GRANT SELECT, INSERT ON provider_register_nonces TO provider_onboarding;
GRANT USAGE, SELECT ON SEQUENCE provider_register_nonces_id_seq TO provider_onboarding;
GRANT SELECT ON provider_auth_policy TO provider_onboarding;

REVOKE ALL ON FUNCTION prune_provider_register_nonces(INTERVAL) FROM PUBLIC;
REVOKE ALL ON FUNCTION prune_provider_register_nonces(INTERVAL) FROM provider_onboarding;
REVOKE ALL ON provider_auth_policy_pending FROM provider_onboarding;
REVOKE ALL ON provider_auth_policy_grants FROM provider_onboarding;
REVOKE ALL ON FUNCTION seed_provider_auth_policy_cutover(TIMESTAMPTZ, TEXT[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION request_provider_auth_policy_exemption(UUID, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION approve_provider_auth_policy_exemption(UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION seed_provider_auth_policy_cutover(TIMESTAMPTZ, TEXT[]) TO provider_onboarding;
GRANT EXECUTE ON FUNCTION request_provider_auth_policy_exemption(UUID, TEXT, TEXT, TIMESTAMPTZ, TEXT, TEXT) TO provider_onboarding;
GRANT EXECUTE ON FUNCTION approve_provider_auth_policy_exemption(UUID, TEXT) TO provider_onboarding;
