package ws

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/augstar/macprovider-coordinator/internal/modelidentity"
)

// spec047PoolStatusFixturePath is the shared SPEC-047-R011 status fixture:
// the Swift CLI and Malibu decoders read the same bytes, so the coordinator
// and both clients are pinned to one wire shape (#1816 F1).
var spec047PoolStatusFixturePath = filepath.Join("..", "..", "..", "testdata", "spec047", "pool_scoped_status_v1.json")

// The fixture is generated from modelAdmissionStatusResponseFromEvent for
// real pool-scoped events; set UPDATE_SPEC047_FIXTURES=1 to rewrite it.
func TestSPEC047PoolScopedStatusSharedFixture(t *testing.T) {
	f := newBindingFixture(t)
	f.server.version = "1.8.210"
	source := wirePoolSource(f)
	source.set(poolSnapshot(testPoolA, 1, poolDigestV1, ggufPoolEntry()))
	f.registerPoolSession(t, poolProvider, "llamacpp_loopback", modelidentity.GGUFFileV1, poolGGUFHash)
	offer := f.offer(t, poolProvider, "q", "llamacpp_loopback", map[string]string{modelidentity.GGUFFileV1: poolGGUFHash})
	f.reevaluate(poolProvider)
	bound := f.latest(t, poolProvider, offer.CandidateID)
	if bound.State != "catalog_priced" || !bound.PoolScoped() {
		t.Fatalf("bind = %+v", bound)
	}
	// Entry removal at the next generation revokes the pool binding; the
	// revoked status still carries pool_binding.
	source.set(poolSnapshot(testPoolA, 2, poolDigestV2))
	f.reevaluate(poolProvider)
	revoked := f.latest(t, poolProvider, offer.CandidateID)
	if revoked.State != modelAdmissionRevoked || !revoked.PoolScoped() {
		t.Fatalf("revoke = %+v", revoked)
	}
	statuses := map[string]any{
		"pool_scoped_catalog_priced": f.server.modelAdmissionStatusResponseFromEvent(bound, false),
		"pool_scoped_revoked":        f.server.modelAdmissionStatusResponseFromEvent(revoked, false),
		"global_offer_submitted":     f.server.modelAdmissionStatusResponseFromEvent(offer, false),
	}
	priced := statuses["pool_scoped_catalog_priced"].(map[string]any)
	if got := priced["allowed_next_states"]; !equalStrings(got, []string{"catalog_priced", "withdrawn", "revoked"}) {
		t.Fatalf("pool-scoped catalog_priced allowed_next_states = %v", got)
	}
	if _, ok := statuses["global_offer_submitted"].(map[string]any)["pool_binding"]; ok {
		t.Fatal("global status carries pool_binding")
	}
	raw, err := json.MarshalIndent(map[string]any{
		"schema":      "spec047_pool_status_fixture.v1",
		"description": "Generated by phase4-coordinator/internal/ws TestSPEC047PoolScopedStatusSharedFixture from modelAdmissionStatusResponseFromEvent; read by the Swift CLI and Malibu decoder tests.",
		"provider_id": poolProvider,
		"statuses":    statuses,
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, '\n')
	if os.Getenv("UPDATE_SPEC047_FIXTURES") == "1" {
		if err := os.WriteFile(spec047PoolStatusFixturePath, raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	committed, err := os.ReadFile(spec047PoolStatusFixturePath)
	if err != nil {
		t.Fatalf("read shared fixture (regenerate with UPDATE_SPEC047_FIXTURES=1): %v", err)
	}
	if !bytes.Equal(committed, raw) {
		t.Fatalf("shared SPEC-047 status fixture drifted from the coordinator; regenerate with UPDATE_SPEC047_FIXTURES=1 and re-run the Swift decoder tests")
	}
}

func equalStrings(got any, want []string) bool {
	values, ok := got.([]string)
	if !ok || len(values) != len(want) {
		return false
	}
	for i := range want {
		if values[i] != want[i] {
			return false
		}
	}
	return true
}
