// Generated by scripts/catalog-release.py. DO NOT EDIT.
package autotune

var permanentlyRejectedReleaseIDs = map[string]struct{}{
	"published-2026-07-07-p2-qwen3-8b": {},
}

func IsPermanentlyRejectedReleaseID(releaseID string) bool {
	_, rejected := permanentlyRejectedReleaseIDs[releaseID]
	return rejected
}
