#!/usr/bin/env bash
# Generate the "Current published release and fleet target" and "Active
# candidate" status lines of docs/releases/cli-release-train.md from live data,
# so that status is never typed by hand. Read-only; prints Markdown on stdout.
#
# Usage: scripts/ops/release-train-status.sh
#
# Sources: GitHub releases, tags and acceptance-candidate runs (gh), the
# public coordinator /healthz (COORDINATOR_URL), and optionally the mirror's
# discovery pointer (MIRROR_LATEST_URL, a latest.json URL). Values that no
# public surface exposes are printed as such, never guessed.
set -euo pipefail
# shellcheck source-path=SCRIPTDIR disable=SC2034  # OPS_NAME is read by lib/common.sh

OPS_NAME=release-train-status
# shellcheck source=lib/common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

repo="$(gh_repo)"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

stable="$(gh release list -R "$repo" --exclude-pre-releases --exclude-drafts -L 1 --json tagName --jq '.[0].tagName')"
[ -n "$stable" ] || die "no stable GitHub release found"
published_at="$(gh release view "$stable" -R "$repo" --json publishedAt --jq .publishedAt)"
(cd "$OPS_TMP_DIR" && gh release download "$stable" -R "$repo" -p compatibility-set.json --clobber >/dev/null 2>&1) || true
compat_id="$(json_field "$OPS_TMP_DIR/compatibility-set.json" 'd["signed"]["compatibility_set_id"]')"

runtime="unreadable"; recommended="unreadable"
if fetch_coordinator_health; then
  runtime="$(json_field "$OPS_TMP_DIR/healthz.json" 'd["version"]')"
  recommended="$(json_field "$OPS_TMP_DIR/healthz.json" 'd["recommended_binary_version"]')"
fi

mirror="not checked (MIRROR_LATEST_URL unset)"
if [ -n "${MIRROR_LATEST_URL:-}" ]; then
  if [ "$(http_get "$MIRROR_LATEST_URL" "$OPS_TMP_DIR/latest.json")" = "200" ]; then
    mirror="$(json_field "$OPS_TMP_DIR/latest.json" 'd.get("tag") or d.get("tag_name") or d.get("version")')"
    mirror="reports \`${mirror:-unparsed}\`"
  else
    mirror="unreadable"
  fi
fi

# Newest acceptance-candidate run and the version its control commit carries.
cand_line="$(workflow_runs acceptance-candidate.yml 1 | head -n1)"
cand_id=""; cand_status=""; cand_concl=""; cand_sha=""; cand_created=""
if [ -n "$cand_line" ]; then
  IFS=$'\t' read -r cand_id cand_status cand_concl cand_sha cand_created <<EOF
$cand_line
EOF
fi
git -C "$REPO_ROOT" fetch -q origin main 2>/dev/null || true
cand_version="$( [ -n "$cand_sha" ] && binary_version_at "$cand_sha" || true)"
cand_tag_state="no tag"
if [ -n "$cand_version" ] && remote_tag_exists "v$cand_version"; then
  cand_tag_state="tag v$cand_version exists"
  if [ "$(gh release view "v$cand_version" -R "$repo" --json isPrerelease --jq .isPrerelease 2>/dev/null || true)" = false ]; then
    cand_tag_state="published as a stable release"
  fi
fi
cand_result="$cand_status"
[ "$cand_status" != completed ] || cand_result="$cand_concl"

url="https://github.com/$repo"
run_cell="none"
[ -z "$cand_id" ] || run_cell="[$cand_id]($url/actions/runs/$cand_id) ($cand_result, created $cand_created)"
cat <<EOF
<!-- generated by scripts/ops/release-train-status.sh at $now; do not edit by hand -->

## Current published release and fleet target

Generated $now from GitHub release metadata and live coordinator health:

| Field | Value |
|---|---|
| GitHub provider release | [$stable]($url/releases/tag/$stable), published $published_at |
| Signed compatibility-set id | \`${compat_id:-unreadable}\` |
| Pearl runtime / recommended provider | \`$runtime\` / \`$recommended\` |
| Compatibility target | not exposed by public health; read the applied coordinator config |
| Mirror discovery | $mirror |

## Active candidate

| Field | Value |
|---|---|
| Newest acceptance run | $run_cell |
| Candidate version / commit | ${cand_version:-unknown} @ \`${cand_sha:-n/a}\` |
| Publication | $cand_tag_state |
EOF
