#!/usr/bin/env python3
"""Regenerate the canonical spec index table in specs/README.md.

The hand-maintained index drifts (it listed SPEC-001..013 while 24 canonical
specs exist). The spec *headers* do not drift — so we derive the index from
them. A file in specs/ is a CANONICAL spec iff:

  1. its first line is a title:   `# SPEC-<NNN> <sep> <Title>`   (sep = — – : -)
  2. it carries a version header:  `**Version:** ...`  in the first 15 lines

Everything else in specs/ (round-N audits, FIX/ABSORB prompts, impl notes,
step docs) is a *supporting* artifact and is intentionally excluded.

Usage:
  python3 scripts/gen_spec_index.py           # rewrite the index in place
  python3 scripts/gen_spec_index.py --check    # exit 1 if the index is stale (CI)

The table is written between these markers in specs/README.md, leaving all
human-authored prose intact:

  <!-- AUTOGEN:spec-index START ... -->
  <!-- AUTOGEN:spec-index END -->
"""
from __future__ import annotations
import glob, os, re, sys

SPECS_DIR = os.path.join(os.path.dirname(__file__), "..", "specs")
README = os.path.join(SPECS_DIR, "README.md")
BEGIN = "<!-- AUTOGEN:spec-index START"
END = "<!-- AUTOGEN:spec-index END -->"

TITLE_RE = re.compile(r"^#\s+SPEC[-\s]0*(\d+)\s*[—–:\-]\s*(.+?)\s*$", re.I)
# Version header is written `**Version:** 1.6 (...)` — the colon sits inside the
# bold markers, so strip all `*` before matching rather than trying to anchor them.
VER_RE = re.compile(r"^Version\s*:\s*(\S+)", re.I)
FNAME_RE = re.compile(r"^SPEC-0*(\d+)-", re.I)


def parse_spec(path: str):
    """Return (num, title, version) if path is a canonical spec, else None.

    num comes from the FILENAME (authoritative); a title/filename number
    mismatch is reported as a warning rather than silently trusted.
    """
    base = os.path.basename(path)
    try:
        head = open(path, encoding="utf-8", errors="replace").read(3000).splitlines()
    except OSError:
        return None
    if not head:
        return None
    tm = TITLE_RE.match(head[0].strip())
    if not tm:
        return None
    version = None
    for line in head[:15]:
        vm = VER_RE.match(line.replace("*", "").strip())
        if vm:
            version = vm.group(1).rstrip(".,;")
            break
    if version is None:
        return None
    fm = FNAME_RE.match(base)
    num = int(fm.group(1)) if fm else int(tm.group(1))
    title_num = int(tm.group(1))
    if fm and title_num != num:
        print(f"WARN {base}: filename says SPEC-{num:03d} but title says "
              f"SPEC-{title_num:03d}", file=sys.stderr)
    return num, tm.group(2).strip(), version


def collect():
    specs, seen = [], {}
    for path in sorted(glob.glob(os.path.join(SPECS_DIR, "*.md"))):
        parsed = parse_spec(path)
        if not parsed:
            continue
        num, title, version = parsed
        rel = os.path.basename(path)
        if num in seen:
            print(f"WARN duplicate canonical SPEC-{num:03d}: "
                  f"{seen[num]} and {rel}", file=sys.stderr)
        seen[num] = rel
        specs.append((num, title, version, rel))
    specs.sort(key=lambda s: (s[0], s[3]))
    # gap report — canonical numbers missing in the 1..max range
    nums = {s[0] for s in specs}
    if nums:
        gaps = [n for n in range(1, max(nums) + 1) if n not in nums]
        if gaps:
            print("NOTE no canonical spec doc for SPEC numbers: "
                  + ", ".join(f"{n:03d}" for n in gaps), file=sys.stderr)
    return specs


def render(specs) -> str:
    rows = ["| SPEC | Title | Version | Link |", "|---|---|---|---|"]
    for num, title, version, rel in specs:
        rows.append(f"| SPEC-{num:03d} | {title} | {version} | [{rel}]({rel}) |")
    return "\n".join(rows)


def splice(readme_text: str, table: str) -> str:
    if BEGIN not in readme_text or END not in readme_text:
        sys.exit(f"error: markers not found in {README}. Add:\n"
                 f"  {BEGIN} -->\n  {END}\naround the index table.")
    pre = readme_text.split(BEGIN, 1)[0]
    post = readme_text.split(END, 1)[1]
    marker_line = (f"{BEGIN} — regenerated by scripts/gen_spec_index.py; "
                   f"do not edit between markers -->")
    return f"{pre}{marker_line}\n{table}\n{END}{post}"


def main() -> int:
    check = "--check" in sys.argv[1:]
    specs = collect()
    print(f"canonical specs: {len(specs)}", file=sys.stderr)
    current = open(README, encoding="utf-8").read()
    updated = splice(current, render(specs))
    if check:
        if current != updated:
            sys.exit("error: specs/README.md is stale — run "
                     "`python3 scripts/gen_spec_index.py` and commit.")
        print("ok: spec index is up to date", file=sys.stderr)
        return 0
    if current != updated:
        open(README, "w", encoding="utf-8").write(updated)
        print(f"updated {README}", file=sys.stderr)
    else:
        print("no change", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
