#!/usr/bin/env python3
"""One-time revocation seed for SPEC-002-R004 (#1914).

Repository admission connects every well-formed release from the target
repository. Releases older than a cutoff are kept off buyer traffic by an
exact, plain list in compatibility_set.revoked_ids: they still connect
update-only and receive the recommendation, so they update themselves.

  generate [--below 1.8.207] [--repo Augustas11/macprovider]
      Network (gh, git ls-remote): every non-draft GitHub release whose tag is
      vMAJOR.MINOR.PATCH below the cutoff and that ships compatibility-set.json.
      Its signed.compatibility_set_id must be canonical and equal
      <repo>:v<ver>@<the tag's peeled commit>. Writes SEED_FILE and the marked
      block in DIST_CONFIG.
  check
      Offline: SEED_FILE is canonical, sorted by version, unique, below its
      recorded cutoff, and the DIST_CONFIG block lists exactly the same ids.
"""
import argparse
import json
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SEED_FILE = ROOT / "phase4-coordinator/dist/compatibility-revoked-ids.txt"
DIST_CONFIG = ROOT / "phase4-coordinator/dist/coordinator.yaml"
BEGIN = "  # BEGIN revoked_ids seed (scripts/legacy-compatibility-revocations.py)\n"
END = "  # END revoked_ids seed\n"
TAG = re.compile(r"^v((?:0|[1-9][0-9]{0,8})\.(?:0|[1-9][0-9]{0,8})\.(?:0|[1-9][0-9]{0,8}))$")
SET_ID = re.compile(r"^([A-Za-z0-9_.-]{1,64}/[A-Za-z0-9_.-]{1,100}):v((?:0|[1-9][0-9]{0,8})\.(?:0|[1-9][0-9]{0,8})\.(?:0|[1-9][0-9]{0,8}))@([0-9a-f]{40})$")


def key(version):
    return tuple(int(x) for x in version.split("."))


def run(cmd):
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def generate(repo, below):
    releases = json.loads(run(["gh", "release", "list", "-R", repo, "-L", "1000",
                               "--json", "tagName,isDraft"]))
    ids = []
    for rel in releases:
        m = TAG.match(rel["tagName"])
        if rel["isDraft"] or not m or key(m.group(1)) >= key(below):
            continue
        tag = rel["tagName"]
        assets = json.loads(run(["gh", "release", "view", tag, "-R", repo, "--json", "assets"]))["assets"]
        if "compatibility-set.json" not in {a["name"] for a in assets}:
            continue
        with tempfile.TemporaryDirectory() as d:
            run(["gh", "release", "download", tag, "-R", repo, "-p", "compatibility-set.json", "-D", d])
            set_id = json.load(open(pathlib.Path(d) / "compatibility-set.json"))["signed"]["compatibility_set_id"]
        # Annotated tags peel to their commit; a lightweight tag names it.
        refs = dict(reversed(line.split("\t")) for line in run(
            ["git", "-C", str(ROOT), "ls-remote", "origin", "refs/tags/%s" % tag, "refs/tags/%s^{}" % tag]).splitlines())
        commit = refs.get("refs/tags/%s^{}" % tag) or refs.get("refs/tags/%s" % tag, "")
        if set_id != "%s:%s@%s" % (repo, tag, commit) or not SET_ID.match(set_id):
            sys.exit("%s: compatibility_set_id %r does not match %s:%s@<tag commit %s>" % (tag, set_id, repo, tag, commit))
        ids.append(set_id)
    ids = sorted(set(ids), key=lambda i: key(SET_ID.match(i).group(2)))
    header = ("# SPEC-002-R004 one-time revocation seed: every non-draft %s release below v%s\n"
              "# that ships compatibility-set.json. Generated by scripts/legacy-compatibility-revocations.py.\n"
              "# below: %s\n" % (repo, below, below))
    SEED_FILE.write_text(header + "".join(i + "\n" for i in ids))
    write_block(ids)
    print("%d ids below v%s written to %s" % (len(ids), below, SEED_FILE.relative_to(ROOT)))


def seed():
    lines = SEED_FILE.read_text().splitlines()
    below = next((l.split(":", 1)[1].strip() for l in lines if l.startswith("# below:")), "")
    return below, [l for l in lines if l and not l.startswith("#")]


def write_block(ids):
    text = DIST_CONFIG.read_text()
    block = BEGIN + "".join('  #       - "%s"\n' % i for i in ids) + END
    if BEGIN in text:
        a = text.index(BEGIN)
        b = text.index(END, a) + len(END)
        text = text[:a] + block + text[b:]
    else:
        anchor = '  #     revoked_ids:\n'
        if text.count(anchor) != 1:
            sys.exit("cannot find the revoked_ids example in %s" % DIST_CONFIG)
        text = text.replace(anchor, anchor + block)
    DIST_CONFIG.write_text(text)


def check():
    below, ids = seed()
    bad = []
    if not TAG.match("v" + below):
        bad.append("missing or bad '# below:' cutoff")
    versions = []
    for i in ids:
        m = SET_ID.match(i)
        if not m:
            bad.append("not canonical: %s" % i)
            continue
        versions.append(key(m.group(2)))
        if TAG.match("v" + below) and key(m.group(2)) >= key(below):
            bad.append("not below v%s: %s" % (below, i))
    if versions != sorted(versions) or len(set(ids)) != len(ids):
        bad.append("ids are not sorted by version and unique")
    text = DIST_CONFIG.read_text()
    if BEGIN not in text:
        bad.append("%s lacks the seed block" % DIST_CONFIG.name)
    else:
        block = text[text.index(BEGIN) + len(BEGIN):text.index(END)]
        if re.findall(r'^  #       - "([^"]+)"$', block, re.M) != ids:
            bad.append("%s seed block differs from %s" % (DIST_CONFIG.name, SEED_FILE.name))
    if bad:
        sys.exit("revocation seed check failed:\n  " + "\n  ".join(bad))
    print("revocation seed ok: %d ids below v%s" % (len(ids), below))


def main():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("generate")
    g.add_argument("--below", default="1.8.207")
    g.add_argument("--repo", default="Augustas11/macprovider")
    sub.add_parser("check")
    args = p.parse_args()
    if args.cmd == "generate":
        if not TAG.match("v" + args.below):
            sys.exit("--below must be canonical MAJOR.MINOR.PATCH")
        generate(args.repo, args.below)
    else:
        check()


if __name__ == "__main__":
    main()
