"""Summarize a SPEC-048-R014 rehearsal evidence directory.

Reads `checks/*.json`, `identity.json`, and `run.json` written by
native_mtp_r014_journey.py and writes `result.json` (closed summary, one row
per R014 item in spec order, with the SHA-256 of every check record) and
`result.md`. Missing items are reported as `NOT_RUN`, never as a pass.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from native_mtp_r014_journey import R014_ITEMS, SCHEMA, now


def summarize(evidence: Path) -> int:
    checks = {}
    for path in sorted((evidence / "checks").glob("*.json")):
        doc = json.loads(path.read_text())
        doc["_sha256"] = hashlib.sha256(path.read_bytes()).hexdigest()
        checks[doc["item"]] = doc
    identity = json.loads((evidence / "identity.json").read_text()) if (evidence / "identity.json").exists() else {}
    run = json.loads((evidence / "run.json").read_text()) if (evidence / "run.json").exists() else {}
    lock = json.loads((evidence / "lab-lock.json").read_text()) if (evidence / "lab-lock.json").exists() else {}
    rows = []
    for item, title in R014_ITEMS:
        doc = checks.get(item)
        rows.append({
            "item": item,
            "title": title,
            "status": doc["status"] if doc else "NOT_RUN",
            "summary": doc["summary"] if doc else "",
            "binary": doc.get("binary", "") if doc else "",
            "check_record": f"checks/{item}.json" if doc else None,
            "check_record_sha256": doc["_sha256"] if doc else None,
        })
    counts = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    result = {
        "schema": SCHEMA,
        "requirement_id": "SPEC-048-R014",
        "evidence_class": "rehearsal_pre_release_no_signature",
        "tuple": {"model_key": "qwen/qwen3.6-35b-a3b", "hardware": identity.get("host"),
                  "qualified_slots": 8, "max_native_active_rows": 1, "max_prompt_tokens": 4096},
        "binaries": {k: identity.get(k) for k in (
            "signed_cli_sha256", "signed_cli_version", "signed_cli_cdhash", "signed_cli_team",
            "release_source_commit", "lab_cli_sha256", "lab_cli_source_commit",
            "signed_cli_contains_lab_journey_command", "metallib_sha256")},
        "lab_lock": lock,
        "run": run,
        "counts": counts,
        "items": rows,
        "generated_at": now(),
    }
    (evidence / "result.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    lines = [
        "# SPEC-048-R014 rehearsal on the published CLI",
        "",
        "Generated by `scripts/native_mtp_r014_journey.py summarize`. Rehearsal evidence only: unsigned,",
        "no CONFORMANCE change, nothing enabled.",
        "",
        f"Signed CLI `{identity.get('signed_cli_version')}` sha256 `{identity.get('signed_cli_sha256')}`, "
        f"cdhash `{identity.get('signed_cli_cdhash')}`; lab build of `{identity.get('lab_cli_source_commit')}` "
        f"sha256 `{identity.get('lab_cli_sha256')}`.",
        "",
        "| R014 item | Status | Binary | Summary | Record |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        summary = row["summary"].replace("|", "\\|")
        lines.append(f"| {row['title']} | **{row['status']}** | {row['binary']} | {summary} | "
                     f"{('`' + row['check_record'] + '`') if row['check_record'] else '-'} |")
    lines += ["", "Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())), ""]
    (evidence / "result.md").write_text("\n".join(lines))
    print(json.dumps(counts, sort_keys=True))
    return 0
